stages:
  preprocess:
    cmd: python scr/data.py
    deps:
    - data/churn_sintetico.csv
    - scr/data.py
    outs:
    - models/preprocessor.joblib  # Cambiá el nombre si tu script genera otro archivo
  train:
    cmd: python scr/train.py
    deps:
    - scr/train.py
    outs:
    - models/best_model.joblib